GEOPY-778
MiraGeoscience/geoapps-utils pull request #10
Opened 2023-11-06 18:39 UTC by jamiefb

2023-11-07 16:07 UTC, domfournier reviewed
Good first stab. Let's talk.

2023-11-07 16:07 UTC, domfournier commented on geoapps_utils/numerical.py
> +    line_ids = points.get_data("line_ids")[0].values
This is too specific for this function, creates a lot of coupling with the method it is used for. Consider adding an argument

2023-11-07 16:07 UTC, domfournier commented on geoapps_utils/numerical.py
> +    channels = points.get_data("channel_group")[0].values
We can probably avoid worrying about the groups if we do this operation one per...

2023-11-10 15:15 UTC, sebhmg commented on geoapps_utils/numerical.py
> +            tri.simplices[:, :2],  # pylint: disable=no-member
to avoid this pylint disable, configure pylintrc as in geoapps (search there for Delaunay)

2023-11-14 17:16 UTC, sebhmg requested changes
better to remove the comment that was commented out

2023-11-14 17:16 UTC, sebhmg commented on geoapps_utils/numerical.py
> +# def combine_edges(
**suggestion (cleanup):** move the comment code away

2023-12-05 23:39 UTC, sebhmg requested changes
please see comment about usage of `getattr`

2023-12-05 23:39 UTC, sebhmg commented on geoapps_utils/numerical.py
> +            simplices[:, ::2],
**suggestion:** `getattr` to circumvent pylint errors is not the right approach

Please see how Delaunay is declared in geoapps pylintrc:

```
# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members=scipy.spatial._qhull.Delaunay.*
```

2023-12-05 23:39 UTC, sebhmg commented on geoapps_utils/numerical.py
> +        and entity_obj.parent is not None
**question:** what the difference between testing though `getattr` and accessing the member directly? Seem redundant

2023-12-06 23:40 UTC, sebhmg reviewed
just scheming through... See a couple of questions

2023-12-06 23:40 UTC, sebhmg commented on geoapps_utils/locations.py
> +        and entity_obj.parent is not None
**question:** is it not enough to test `entity_obj.parent is not None`

`parent` is defined property of `Entity`

2023-12-06 23:40 UTC, sebhmg commented on geoapps_utils/geophysical_systems.py
> +                [-0.0000e00, 0.0000e00],
**question (readability):** could this be generated with increment of `2.5e-05` instead of hard-coding it all?

2023-12-08 18:35 UTC, sebhmg submitted a review, later dismissed

2023-12-13 17:24 UTC, jamiefb reviewed
Just a couple docstrings to fix

2023-12-13 17:24 UTC, jamiefb commented on geoapps_utils/numerical.py
> +    :param damping: Maximum angle between points in a curve, in radians.
```suggestion
    :param damping: Damping factor between [0, 1] for the path roughness.
```

2023-12-13 17:24 UTC, jamiefb commented on geoapps_utils/numerical.py
> +):
```suggestion
) -> tuple[list, np.ndarray]:
```

2023-12-13 17:24 UTC, jamiefb commented on geoapps_utils/numerical.py
> +    :param ind: Index of incoming edge.
```suggestion
    :param incoming: Incoming edge.
```

2023-12-13 20:57 UTC, domfournier commented
thanks @jamiefb for the fixes. One more round please

2023-12-13 20:58 UTC, domfournier approved these changes

2023-12-13 21:05 UTC, merged