GEOPY-1688
MiraGeoscience/geoapps-utils pull request #72
Opened 2024-07-25 15:03 UTC by MatthieuCMira

Accept BaseData as params

2024-07-25 17:07 UTC, domfournier reviewed
looks good. Minor comments. Also we might have to remove this line. If the pydantic class is frozen, then this would make it to crash

![image](https://github.com/user-attachments/assets/fe5828fb-363d-4af4-8072-8ecac22b31dc)

2024-07-25 17:07 UTC, domfournier commented on geoapps_utils/driver/driver.py
> +    def __init__(self, params: BaseParams | BaseData):
While at it, can we make the input attributes more explicit in the init?

```suggestion
    def __init__(self, params: BaseParams | BaseData):
        self.params = params
        self.workspace = params.geoh5
        self.out_group = params.out_group
```

2024-07-25 17:07 UTC, domfournier commented on geoapps_utils/driver/driver.py
>          """
This goes in the signature of the class.

2024-07-25 18:34 UTC, MatthieuCMira commented
Overall question:

I removed some __init__ from the assets. 
Pylint did not like this file, and I had no idea why it was there. 
Is there a good reason to keep this file?

2024-07-25 21:38 UTC, MatthieuCMira commented
Cannot change much in BaseDriver.
Simpeg Driver seems quite hacky using not straight forwards mechanics...

2024-07-25 21:48 UTC, domfournier commented on geoapps_utils/driver/data.py
> +        }
Why the change? Both seems to do the same thing, just more compact.

2024-07-26 12:13 UTC, MatthieuCMira commented
> looks good. Minor comments. Also we might have to remove this line. If the pydantic class is frozen, then this would make it to crash
> 
> ![image](https://private-user-images.githubusercontent.com/55204635/352227087-fe5828fb-363d-4af4-8072-8ecac22b31dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTYxMDEsIm5iZiI6MTcyMTk5NTgwMSwicGF0aCI6Ii81NTIwNDYzNS8zNTIyMjcwODctZmU1ODI4ZmItMzYzZC00YWY0LTgwNzItOGVjYWMyMmIzMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEyMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MTFhY2FkZGY0YmZkZGM5ZTExOWJiZDAyMmYzNGQ3OWY1OWEwNDc2MGZhZGE0MzRkMmM5OTM3ZTA3NjJmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OfItgrMYt9s3Ro9RW0Ct1SLkxHCuGA5Xnxeo9iW9k24)

This line is probably the result of some hacky Simpeg driver processes. 
We should first refactor this package before changing it

2024-07-26 14:23 UTC, MatthieuCMira commented
I added a function to create the params in the driver directly from a uijson. 

So driver creation can be more straight forward 

(option for BaseData Only)

2024-07-26 16:29 UTC, domfournier reviewed
I am not sold on the `create_from_input_file` method. It is duplicating a lot of the mechanics of `BaseData.build`, and mixing the input type for params...

2024-07-26 16:29 UTC, domfournier commented on geoapps_utils/driver/driver.py
> +            return self._params_class(**params_dict)
Use the `build` method of `BaseData` instead so we can handle nested Models

2024-07-26 16:29 UTC, domfournier commented on geoapps_utils/driver/driver.py
> +            "Input file must be of type str, Path, or geoh5py.ui_json.InputFile,"
Split the raise so it's clearer why it failed and do it before the return. First check that input_file was valid, then check that `_param_class` is type BaseData.

2024-07-26 16:29 UTC, domfournier commented on geoapps_utils/driver/driver.py
> +        Create driver from input file.
Looks like it's creating a params, not a driver. Type the return too...

2024-07-26 16:29 UTC, domfournier commented on geoapps_utils/driver/driver.py
> +        if isinstance(val, (str, Path, InputFile)):
I am not a fan of this, we are mixing what params can be. Feels like you want to have an `input_file` setter instead, and do the setting there instead.

2024-07-26 19:05 UTC, MatthieuCMira commented
Well, the "start" classmethod is already waht we wanted to do.

2024-07-30 16:06 UTC, benk-mira requested changes
I think we should spend a bit more time on the input_file stuff.  It seems like we're losing the ability to carry extra parameters through.

2024-07-31 18:20 UTC, benk-mira requested changes

2024-07-31 19:48 UTC, benk-mira approved these changes

2024-07-31 19:49 UTC, merged