GEOPY-760
MiraGeoscience/geoapps-utils pull request #89
Opened 2024-11-06 18:38 UTC by domfournier

2024-11-06 22:03 UTC, benk-mira requested changes
Looks good

2024-11-06 22:03 UTC, benk-mira commented on geoapps_utils/utils/numerical.py
> +def fit_circle(x_val: np.ndarray, y_val) -> tuple:
```suggestion
def fit_circle(x_val: np.ndarray, y_val) -> tuple[float, np.ndarray, np.ndarray]:
```

2024-11-06 22:03 UTC, benk-mira commented on geoapps_utils/utils/numerical.py
> +    :return: radius, x0, y0
docstring these individually:
```
:return radius: blah blah.
:return x0: blah blah.
:return y0: and on and on.
```

2024-11-06 22:46 UTC, domfournier commented on geoapps_utils/utils/numerical.py
> +    radius = (coef[0] ** 2.0 + coef[1] ** 2.0 + coef[2]) ** 0.5
No the last coefficient represents x0**2 + y0**2 - r**2

2024-11-06 22:46 UTC, domfournier commented on geoapps_utils/utils/numerical.py
> +    radius = (coef[0] ** 2.0 + coef[1] ** 2.0 + coef[2]) ** 0.5
I added notes in the docstrings

2024-11-07 21:51 UTC, benk-mira approved these changes
thanks for the docstring updates

2024-11-07 22:12 UTC, merged